#pragma once
#include <Arduino.h>

// Glyph tables generated by font_design/gen_font.py into font_data.cpp.
// Only font.cpp should need these; everything else goes through font.h.

struct FontGlyph {
  const char *token;         // what's typed to get it: "A", "\xC3\x86" (Æ), ":smile:"
  uint8_t width;             // columns, not counting inter-glyph spacing
  const uint16_t *columns;   // left to right; bit 15 = top row ... bit 0 = bottom
};

// One table per font in font.h's Font enum.
extern const FontGlyph FONT_SPLEEN[];
extern const size_t FONT_SPLEEN_COUNT;
extern const FontGlyph FONT_DRIP[];
extern const size_t FONT_DRIP_COUNT;
extern const FontGlyph FONT_DRIP_BOLD[];
extern const size_t FONT_DRIP_BOLD_COUNT;

// Same in every font, one entry per emoji, keyed by its shortcode.
extern const FontGlyph FONT_EMOJI[];
extern const size_t FONT_EMOJI_COUNT;
