#pragma once
#include <Arduino.h>

// Glyph tables generated by font_design/gen_font.py into font_data.cpp.
// Only font.cpp should need these; everything else goes through font.h.

struct FontGlyph {
  const char *token;         // what's typed to get it: "A", "\xC3\x86" (Æ), ":-)"
  uint8_t width;             // columns, not counting inter-glyph spacing
  const uint16_t *columns;   // left to right; bit 15 = top row ... bit 0 = bottom
};

extern const FontGlyph FONT_REGULAR[];
extern const size_t FONT_REGULAR_COUNT;
extern const FontGlyph FONT_BOLD[];
extern const size_t FONT_BOLD_COUNT;

// Same in every weight. Several tokens can share one drawing (":-)" and ":)").
extern const FontGlyph FONT_EMOJI[];
extern const size_t FONT_EMOJI_COUNT;
